apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: kpwvu1zzb-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kpwvu1zzb-go 
  name: kpwvu1zzb-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: kpwvu1zzb-go 
